config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'
  # resources :companies
  resources :companies do
    member do
      get 'up'
      get 'down'
      get 'remove_img'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates_presence_of :name ,:apply_site 
  
  def short_description
    if memo.length <= 9
      memo
    else
     memo[0, 9] + '...'
    end
  end

  def short_content
    if content.length <= 9
      content
    else
      content[0, 9] + '...'
    end 
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company , only: %i[show edit update destroy up down remove_img]
  before_action :set_companies , only: %i[up down]

  def index
    @companies = Company.all.order(:sequence)
  end

  def show
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_paramas)
    if @company.save 
      @company.sequence = @company.id
      @company.save
      redirect_to root_path
    else
      render new_company_path
    end
  end

  def edit
  end
  
  def update
    if @company.update(company_paramas)
    redirect_to company_path
    else
      render :edit
    end
  end
  
  def destroy
    @company.destroy
    @company.remove_avatar!
    redirect_to root_path
  end

  def remove_img
    @company.remove_avatar!
    @company.save
    render :edit
  end

  def up
    @companies[@i].sequence , @companies[@i-1].sequence = @companies[@i-1].sequence , @companies[@i].sequence
    redirect_to root_path if @companies[@i].save && @companies[@i-1].save  
  end

  def down
    @companies[@i].sequence , @companies[@i+1].sequence = @companies[@i+1].sequence , @companies[@i].sequence
    redirect_to root_path if @companies[@i].save && @companies[@i+1].save  
  end


  private
  def company_paramas
    params.require(:company).permit(:name,:content,:memo,:apply_site,:hp,:recruit_status,:avatar)
  end
  def set_company
    @company = Company.find(params[:id])
  end
  def set_companies
    @companies = Company.all.order(:sequence)
    @i = @companies.ids.index(@company.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def print_recruit_status(company)
    case company.recruit_status
    when 1
      "検討中"
    when 2
      "応募済み-書類選考"
    when 3
      "応募済み-面接"
    when 4
      "内定"
    when 5
      "不合格"
    when 6
      "返信待ち"
    else 
      "不明"
    end
  end

  
  
end

app/views/companies/_form.html.erb
<%= form_with model: @company, loal: true do |f| %>
<form>
  <div class="form-group">
    
    <%= f.label :name, "会社名"  %>  
    <%= f.text_field :name, class: 'form-control',placeholder: "Example.Co",value: @company.name %>
    
    <%= f.label :content, "事業内容" %>
    <%= f.text_field :content, class: 'form-control',placeholder: "ex:受託開発",value: @company.content %>

    <%= f.label :memo, "メモ" %>
    <%= f.text_area :memo, class: "form-control", rows: "3", value:@company.memo  %>

    <%= f.label :apply_site, "募集サイト" %>
    <%= f.text_field :apply_site, class:'form-control',placeholder:"example/recruit.com" ,value:@company.apply_site %>

    <%= f.label :hp, "企業HP" %>
    <%= f.text_field :hp ,class: "form-control", placeholder:"Example.com" ,value:@company.hp%>

    <%= f.label :recruit_status, "応募状況" %>
    <%= f.select :recruit_status, [["選択"],["検討中",1],["応募済み-書類選考",2],["応募済み-面接",3],["内定",4],["不合格",5],["返信待ち",6]] ,{},{class:"form-control"} %>
    <div>
      <%= f.label :avatar, "写真" %>
    </div>
    <%= render 'shared/avatar_icon' %>
    <% if @company.avatar? %>
      <%= link_to "削除", remove_img_company_path(@company.id), data: { confirm: '本当に削除しますか?' }%>
    <% end %>
    <%= f.file_field :avatar ,multipart: true,class: "form-control-file" %>
    <br>
    <%= link_to "戻る", root_path, class: 'btn btn-light' %>
    <%= f.submit nil , disable_with: '追加中...', class:"btn btn-primary"%>
  </div>
</form>
<% end %>

app/views/companies/edit.html.erb
<div class="container">
  <h1>
    <%= @company.name %>
  </h1>
  <%= render 'shared/error_msg' %>
  <%= render 'form' %>
</div>

app/views/companies/index.html.erb
<div class="container">
<h1 class="headline">会社応募リスト</h1>
<!-- <p>Find me in app/views/companies/index.html.erb</p> -->

  <%= link_to "New", new_company_path,class: 'btn btn-outline-secondary' %>


<table class="table">
  <thead>
  <tr>
    <th scope="col">
      # 
    </th>
    <th scope="col">
      会社名 
    </th>
    <th scope="col">
      仕事内容
    </th>
    <th scope="col">
      メモ
    </th>

    <th scope="col">
      順位
    </th>
    <th scope="col">
      応募状況
    </th>
    <th scope="col">
      
    </th>
    <th scope="col">
      
    </th>
  </tr>
</thead>
<tbody>
  <% @companies.each_with_index do |company , idx| %>
  <tr>
    <td scope="row">
      <%= idx+1 %>
    </td>
    <td scope="row">
      <%= company.name %>
    </td>
    <td scope="row">
      <%= company.short_content %>
    </td>
    <td scope="row">
      <%= company.short_description %>
    </td>
  
    <td scope="row">
      <% if idx != 0 %>
        <%= link_to up_company_path(company) do %>
          <i class="fas fa-chevron-up"></i>
        <% end %>
      <% end %>
      <% if idx+1 != @companies.length %>
        <%= link_to down_company_path(company) do %>
          <i class="fas fa-chevron-down"></i>
        <% end %>
      <% end %>
      <!-- https://qiita.com/knt45/items/c76b246ad448f3814ae4 -->
    </td>
    <td scope="row">
      <%= print_recruit_status(company) %>
    </td>
    <td scope="row">
       <%= link_to "詳細", company_path(company) %>
    </td>
    <td scope="row">
      <%= link_to "編集", edit_company_path(company) %>
    </td>
    <td scope="row">
      <%= link_to "✖️", company_path(company), method: :delete , data: { confirm: '本当に削除しますか?' }  %>
    </td>
  </tr>
  <% end %>

  <tr>

  </tr>
</tbody>
</table>
</div>

app/views/companies/new.html.erb
<div class="container">

  <h1>企業追加</h1>
  <!-- <p>Find me in app/views/companies/new.html.erb</p> -->
    <%= render 'shared/error_msg' %>
    <%= render 'form' %>
</div>

app/views/companies/show.html.erb
<div class="container">
<h1 class="headline" ><%= @company.name %></h1>

<%= render 'shared/avatar_icon' %>
<div>
  <h3>仕事内容</h3>
  <p><%= @company.content %></p>
  <h3>メモ</h3>
  <p><%= @company.memo %></p>
  <h3>応募サイト</h3>
  <p><%= @company.apply_site %></p>
  <h3>企業HP</h3>
  <p><%= @company.hp %></p>
  <h3>現在状況</h3>
  <p>
    <%= print_recruit_status(@company) %>
  </p>
</div>

<%= link_to "戻る", root_path , class: 'btn btn-outline-secondary' %>
<%= link_to "編集", edit_company_path(@company.id) , class: 'btn btn-outline-secondary' %>
<%= link_to "削除", company_path(@company.id) ,method: :delete, class: 'btn btn-outline-secondary', data: { confirm: '本当に削除しますか?' } %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_avatar_icon.html.erb
<% if @company.avatar? %>
    <%= image_tag @company.avatar.thumb.url %>
<% else %>
    <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg", :size => '100x100' %>
<% end %>

app/views/shared/_error_msg.html.erb
<div class="form-body">
  <% @company.errors.full_messages.each do | m |%>
    <li class="form-error">
      <%= m %>
    </li>
  <% end %>
</div>